apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: ${KARGO_PROJECT}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ${KARGO_PROJECT}-repo
  namespace: ${KARGO_PROJECT}
  labels:
    kargo.akuity.io/cred-type: git
stringData:
  repoURL: ${GITOPS_REPO_URL}
  username: ${GITHUB_USERNAME}
  password: ${GITHUB_PAT}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: ${KARGO_PROJECT}
  namespace: ${KARGO_PROJECT}
spec:
  subscriptions:
  - image:
      repoURL: ghcr.io/linuxcontainers/alpine
      semverConstraint: ^3.0
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: ${KARGO_PROJECT}
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: ${KARGO_PROJECT}
    sources:
      direct: true
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: ${GITOPS_REPO_URL}
      writeBranch: main
      kustomize:
        images:
        - image: ghcr.io/linuxcontainers/alpine
          path: basic/stages/test
    argoCDAppUpdates:
    - appName: ${KARGO_PROJECT}-test
      appNamespace: argocd
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: ${KARGO_PROJECT}
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: ${KARGO_PROJECT}
    sources:
      stages:
      - test
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: ${GITOPS_REPO_URL}
      writeBranch: main
      kustomize:
        images:
        - image: ghcr.io/linuxcontainers/alpine
          path: basic/stages/uat
    argoCDAppUpdates:
    - appName: ${KARGO_PROJECT}-uat
      appNamespace: argocd
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: ${KARGO_PROJECT}
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: ${KARGO_PROJECT}
    sources:
      stages:
      - uat
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: ${GITOPS_REPO_URL}
      writeBranch: main
      kustomize:
        images:
        - image: ghcr.io/linuxcontainers/alpine
          path: basic/stages/prod
    argoCDAppUpdates:
    - appName: ${KARGO_PROJECT}-prod
      appNamespace: argocd